all: carLists postScript

carLists:
	gcc -Wall -std=c99 -Iinclude src/linkedList.c src/carLists.c src/carMain.c -o carLists

postScript:
	gcc -Wall -std=c99 -Iinclude src/postScript.c src/postMain.c -o postScript

