all: treeMain heapMain

treeMain:
	gcc -Wall -std=c99 -Iinclude src/treeMain.c src/mathTree.c src/tree.c -lm -o treeMain

heapMain:
	gcc -Wall -std=c99 -o heapMain -Iinclude src/heapMain.c src/runHeap.c

